// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageStatus int32

const (
	MessageStatus_OK           MessageStatus = 0
	MessageStatus_BAD_REQUEST  MessageStatus = 1
	MessageStatus_UNAUTHORIZED MessageStatus = 2
	MessageStatus_FORBIDDEN    MessageStatus = 3
	MessageStatus_NOT_FOUND    MessageStatus = 4
)

// Enum value maps for MessageStatus.
var (
	MessageStatus_name = map[int32]string{
		0: "OK",
		1: "BAD_REQUEST",
		2: "UNAUTHORIZED",
		3: "FORBIDDEN",
		4: "NOT_FOUND",
	}
	MessageStatus_value = map[string]int32{
		"OK":           0,
		"BAD_REQUEST":  1,
		"UNAUTHORIZED": 2,
		"FORBIDDEN":    3,
		"NOT_FOUND":    4,
	}
)

func (x MessageStatus) Enum() *MessageStatus {
	p := new(MessageStatus)
	*p = x
	return p
}

func (x MessageStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_user_proto_enumTypes[0].Descriptor()
}

func (MessageStatus) Type() protoreflect.EnumType {
	return &file_user_proto_enumTypes[0]
}

func (x MessageStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageStatus.Descriptor instead.
func (MessageStatus) EnumDescriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

type UserStatus int32

const (
	UserStatus_ACTIVE    UserStatus = 0
	UserStatus_INACTIVE  UserStatus = 1
	UserStatus_DELETED   UserStatus = 2
	UserStatus_SUSPENDED UserStatus = 3
)

// Enum value maps for UserStatus.
var (
	UserStatus_name = map[int32]string{
		0: "ACTIVE",
		1: "INACTIVE",
		2: "DELETED",
		3: "SUSPENDED",
	}
	UserStatus_value = map[string]int32{
		"ACTIVE":    0,
		"INACTIVE":  1,
		"DELETED":   2,
		"SUSPENDED": 3,
	}
)

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}

func (x UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_user_proto_enumTypes[1].Descriptor()
}

func (UserStatus) Type() protoreflect.EnumType {
	return &file_user_proto_enumTypes[1]
}

func (x UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatus.Descriptor instead.
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int32                 `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	ReferralCode  *string                `protobuf:"bytes,2,opt,name=referralCode,proto3,oneof" json:"referralCode,omitempty"`
	UserName      string                 `protobuf:"bytes,3,opt,name=userName,proto3" json:"userName,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Status        *UserStatus            `protobuf:"varint,5,opt,name=status,proto3,enum=grpc.UserStatus,oneof" json:"status,omitempty"`
	CreatedAt     *string                `protobuf:"bytes,6,opt,name=createdAt,proto3,oneof" json:"createdAt,omitempty"`
	UpdatedAt     *string                `protobuf:"bytes,7,opt,name=updatedAt,proto3,oneof" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *User) GetReferralCode() string {
	if x != nil && x.ReferralCode != nil {
		return *x.ReferralCode
	}
	return ""
}

func (x *User) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetStatus() UserStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return UserStatus_ACTIVE
}

func (x *User) GetCreatedAt() string {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return ""
}

func (x *User) GetUpdatedAt() string {
	if x != nil && x.UpdatedAt != nil {
		return *x.UpdatedAt
	}
	return ""
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReferralCode  string                 `protobuf:"bytes,1,opt,name=referralCode,proto3" json:"referralCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserRequest) GetReferralCode() string {
	if x != nil {
		return x.ReferralCode
	}
	return ""
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReferralCode  string                 `protobuf:"bytes,1,opt,name=referralCode,proto3" json:"referralCode,omitempty"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserRequest) GetReferralCode() string {
	if x != nil {
		return x.ReferralCode
	}
	return ""
}

func (x *UpdateUserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReferralCode  string                 `protobuf:"bytes,1,opt,name=referralCode,proto3" json:"referralCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteUserRequest) GetReferralCode() string {
	if x != nil {
		return x.ReferralCode
	}
	return ""
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        MessageStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=grpc.MessageStatus" json:"status,omitempty"`
	Data          *User                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *UserResponse) GetStatus() MessageStatus {
	if x != nil {
		return x.Status
	}
	return MessageStatus_OK
}

func (x *UserResponse) GetData() *User {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x04grpc\"\xaa\x02\n" +
	"\x04User\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x05H\x00R\x02id\x88\x01\x01\x12'\n" +
	"\freferralCode\x18\x02 \x01(\tH\x01R\freferralCode\x88\x01\x01\x12\x1a\n" +
	"\buserName\x18\x03 \x01(\tR\buserName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12-\n" +
	"\x06status\x18\x05 \x01(\x0e2\x10.grpc.UserStatusH\x02R\x06status\x88\x01\x01\x12!\n" +
	"\tcreatedAt\x18\x06 \x01(\tH\x03R\tcreatedAt\x88\x01\x01\x12!\n" +
	"\tupdatedAt\x18\a \x01(\tH\x04R\tupdatedAt\x88\x01\x01B\x05\n" +
	"\x03_idB\x0f\n" +
	"\r_referralCodeB\t\n" +
	"\a_statusB\f\n" +
	"\n" +
	"_createdAtB\f\n" +
	"\n" +
	"_updatedAt\"3\n" +
	"\x11CreateUserRequest\x12\x1e\n" +
	"\x04user\x18\x01 \x01(\v2\n" +
	".grpc.UserR\x04user\"4\n" +
	"\x0eGetUserRequest\x12\"\n" +
	"\freferralCode\x18\x01 \x01(\tR\freferralCode\"W\n" +
	"\x11UpdateUserRequest\x12\"\n" +
	"\freferralCode\x18\x01 \x01(\tR\freferralCode\x12\x1e\n" +
	"\x04user\x18\x02 \x01(\v2\n" +
	".grpc.UserR\x04user\"7\n" +
	"\x11DeleteUserRequest\x12\"\n" +
	"\freferralCode\x18\x01 \x01(\tR\freferralCode\"[\n" +
	"\fUserResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\x0e2\x13.grpc.MessageStatusR\x06status\x12\x1e\n" +
	"\x04data\x18\x02 \x01(\v2\n" +
	".grpc.UserR\x04data*X\n" +
	"\rMessageStatus\x12\x06\n" +
	"\x02OK\x10\x00\x12\x0f\n" +
	"\vBAD_REQUEST\x10\x01\x12\x10\n" +
	"\fUNAUTHORIZED\x10\x02\x12\r\n" +
	"\tFORBIDDEN\x10\x03\x12\r\n" +
	"\tNOT_FOUND\x10\x04*B\n" +
	"\n" +
	"UserStatus\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x00\x12\f\n" +
	"\bINACTIVE\x10\x01\x12\v\n" +
	"\aDELETED\x10\x02\x12\r\n" +
	"\tSUSPENDED\x10\x032\xf3\x01\n" +
	"\vUserService\x129\n" +
	"\n" +
	"CreateUser\x12\x17.grpc.CreateUserRequest\x1a\x12.grpc.UserResponse\x123\n" +
	"\aGetUser\x12\x14.grpc.GetUserRequest\x1a\x12.grpc.UserResponse\x129\n" +
	"\n" +
	"UpdateUser\x12\x17.grpc.UpdateUserRequest\x1a\x12.grpc.UserResponse\x129\n" +
	"\n" +
	"DeleteUser\x12\x17.grpc.DeleteUserRequest\x1a\x12.grpc.UserResponseB\x1bZ\x19go-grpc-clean/internal/pbb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_user_proto_goTypes = []any{
	(MessageStatus)(0),        // 0: grpc.MessageStatus
	(UserStatus)(0),           // 1: grpc.UserStatus
	(*User)(nil),              // 2: grpc.User
	(*CreateUserRequest)(nil), // 3: grpc.CreateUserRequest
	(*GetUserRequest)(nil),    // 4: grpc.GetUserRequest
	(*UpdateUserRequest)(nil), // 5: grpc.UpdateUserRequest
	(*DeleteUserRequest)(nil), // 6: grpc.DeleteUserRequest
	(*UserResponse)(nil),      // 7: grpc.UserResponse
}
var file_user_proto_depIdxs = []int32{
	1, // 0: grpc.User.status:type_name -> grpc.UserStatus
	2, // 1: grpc.CreateUserRequest.user:type_name -> grpc.User
	2, // 2: grpc.UpdateUserRequest.user:type_name -> grpc.User
	0, // 3: grpc.UserResponse.status:type_name -> grpc.MessageStatus
	2, // 4: grpc.UserResponse.data:type_name -> grpc.User
	3, // 5: grpc.UserService.CreateUser:input_type -> grpc.CreateUserRequest
	4, // 6: grpc.UserService.GetUser:input_type -> grpc.GetUserRequest
	5, // 7: grpc.UserService.UpdateUser:input_type -> grpc.UpdateUserRequest
	6, // 8: grpc.UserService.DeleteUser:input_type -> grpc.DeleteUserRequest
	7, // 9: grpc.UserService.CreateUser:output_type -> grpc.UserResponse
	7, // 10: grpc.UserService.GetUser:output_type -> grpc.UserResponse
	7, // 11: grpc.UserService.UpdateUser:output_type -> grpc.UserResponse
	7, // 12: grpc.UserService.DeleteUser:output_type -> grpc.UserResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	file_user_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		EnumInfos:         file_user_proto_enumTypes,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
